from NekoMimi import utils as nm

_ver = nm.read("./version.txt").split("\n")[0]

_st = nm.read("./setuptemplate.py")
_st = _st.replace("<PLACEHOLDER>", _ver)

nm.write(_st, "./setup.py")

v_line = f"__version__ = '{_ver}'"

description = """
\"\"\"
Version of the Implug plugin system
More info at the Docs section on GH

init file generated by build script
\"\"\"
"""

contents = f"{v_line}{description}" 

nm.write(contents, "./Implug/__init__.py")
print(f"Built build process files v{_ver}")
